@Omni.Web_HostAddress = http://localhost:5167

GET {{Omni.Web_HostAddress}}/weatherforecast/
Accept: application/json

###

### Flights - list all
GET {{Omni.Web_HostAddress}}/flights
Accept: application/json

###

### Flights - get by id
GET {{Omni.Web_HostAddress}}/flights/1
Accept: application/json

###

### Flights - create
POST {{Omni.Web_HostAddress}}/flights
Content-Type: application/json

{
  "flightNumber": "RO621",
  "aircraft": "YR-BGA",
  "origin": "OTP",
  "destination": "OMR",
  "scheduledDeparture": "2026-03-06T06:00:00Z",
  "actualDeparture": "2026-03-06T06:00:00Z",
  "scheduledArrival": "2026-03-06T07:00:00Z",
  "actualArrival": "2026-03-06T07:00:00Z",
  "gateId": 2,
  "runwayId": 1,
  "baggageConveyorBeltId": 1,
  "passengerNumber": 68,
  "baggageTotalChecked": 45
}

###

### Flights - update (replace)
PUT {{Omni.Web_HostAddress}}/flights/1
Content-Type: application/json

{
  "flightId": 1,
  "flightNumber": "RO621",
  "aircraft": "YR-BGA",
  "origin": "OTP",
  "destination": "OMR",
  "scheduledDeparture": "2026-03-06T06:00:00Z",
  "actualDeparture": "2026-03-06T06:05:00Z",
  "scheduledArrival": "2026-03-06T07:00:00Z",
  "actualArrival": "2026-03-06T07:05:00Z",
  "gateId": 1,
  "runwayId": 1,
  "baggageConveyorBeltId": 1,
  "passengerNumber": 68,
  "baggageTotalChecked": 45
}

###

### Flights - delete
DELETE {{Omni.Web_HostAddress}}/flights/1

###

### Gates - list all
GET {{Omni.Web_HostAddress}}/gates
Accept: application/json

###

### Runways - list all
GET {{Omni.Web_HostAddress}}/runways
Accept: application/json

###

### Baggage Conveyor Belts - list all
GET {{Omni.Web_HostAddress}}/baggageconveyorbelts
Accept: application/json

###

### Disruptions - list all
GET {{Omni.Web_HostAddress}}/disruptions
Accept: application/json

###

### Disruptions - create
POST {{Omni.Web_HostAddress}}/disruptions
Content-Type: application/json

{
  "resourceType": "Gate",
  "resourceId": 1
}

###

### Disruptions - solve
POST {{Omni.Web_HostAddress}}/disruptions/1/solve

###
