// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Omni.Web.Data;

#nullable disable

namespace Omni.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306184235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Omni.Web.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActualArrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActualDeparture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aircraft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaggageConveyorBelt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaggageTotalChecked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewFlightAttendants")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewPilots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PassengerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Runway")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledArrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledDeparture")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
