// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Omni.Web.Data;

#nullable disable

namespace Omni.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307090054_FlightTimesToDateTimeAndOptional_RemoveCrew")]
    partial class FlightTimesToDateTimeAndOptional_RemoveCrew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Omni.Web.Models.Disruption", b =>
                {
                    b.Property<int>("DisruptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DisruptionId");

                    b.ToTable("Disruptions");
                });

            modelBuilder.Entity("Omni.Web.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aircraft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaggageConveyorBelt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaggageTotalChecked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PassengerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunwayId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScheduledArrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledDeparture")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Omni.Web.Models.Gate", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GateId");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("Omni.Web.Models.Runway", b =>
                {
                    b.Property<int>("RunwayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RunwayId");

                    b.ToTable("Runways");
                });
#pragma warning restore 612, 618
        }
    }
}
